name: qone.io
description: yet another developer blog
meta_description: "yet another developer blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /
domain_name: 'http://qone.io'
google_analytics: 'UA-60513025-1'

# Details for the RSS feed generator
url:            'http://qone.io'
author:         'Alexander Brandstedt'
